### ISSUE TITLE
was this tested on ubuntu 14?

### ISSUE THREAD

**Issue by tzvikaz** [vkhatri/chef-icinga2#24]
Tried installing only the basics with classic ui.
this is my role: (had to override version for it not to fail)

name "icinga2-server"
description "iIcinga2 Server"
run_list(
  "role[linux-base]",
  "recipe[icinga2::server]",
  "recipe[icinga2::server_apache]",
  "recipe[icinga2::server_core]",
  "recipe[icinga2::server_classic_ui]",
  #"recipe[icinga2::server_ido_schema]",
  #"recipe[icinga2::server_pnp]",
  #"recipe[icinga2::server_web2]"
) 
default_attributes(
  'icinga2' => {
    'version' => '2.2.4-1',
    'classic_ui' => {
      'version' => '2.2.4-1'
    }
  }
)

chef-client run fine. but 404 on http://server_ip/icinga2-classicui.

any idea?

**Comment by vkhatri** [comment]
@tzvikaz this cookbook is no longer maintained in this repo and has been transferred to - https://github.com/icinga/chef-icinga2.

plenty of issues have been resolved for ubuntu lately, but i never got time to finish full testing.

you may give a try to https://github.com/icinga/chef-icinga2

**Comment by zitzman** [comment]
Thanks!

I Was actually referring to the icinga/chef-icinga2
https://github.com/icinga/chef-icinga2 repo and not the one I commented
at by mistake.

On Mon, Feb 16, 2015 at 9:43 PM, Virender Khatri notifications@github.com
wrote:

> @tzvikaz https://github.com/tzvikaz this cookbook is no longer
> maintained in this repo and has been transferred to -
> https://github.com/icinga/chef-icinga2.
> 
> plenty of issues have been resolved for ubuntu lately, but i never got
> time to finish full testing.
> 
> you may give a try to https://github.com/icinga/chef-icinga2
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/vkhatri/chef-icinga2/issues/24#issuecomment-74562220.

## 

_Tzvika Zitzman_

_CloudShare, Ltd. http://www.cloudshare.com/_
_The Easiest Way to Bring Your Business Application to the Cloud_
@CloudShare https://twitter.com/CloudShare | Blog
http://blog.cloudshare.com/ | TechBlog http://techblog.cld.sr/ |
LinkedIn https://www.linkedin.com/company/cloudshare

**Comment by vkhatri** [comment]
classic ui is not working for current release 2.2.4-1 - https://dev.icinga.org/issues/8387 and cookbook does not support apt snapshot repo at this point, i am going to fix it this week along with few minor bugs.

next release should have all the bugs fixes for ubuntu platform.

**Comment by zitzman** [comment]
splendid! thanks.

On Mon, Feb 16, 2015 at 10:27 PM, Virender Khatri notifications@github.com
wrote:

> classic ui is not working for current release 2.2.4-1 -
> https://dev.icinga.org/issues/8387 and cookbook does not support apt
> snapshot repo at this point, i am going to fix it this week along with few
> minor bugs.
> 
> next release should have all the bugs fixes for ubuntu platform.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/vkhatri/chef-icinga2/issues/24#issuecomment-74567603.

## 

_Tzvika Zitzman_

_CloudShare, Ltd. http://www.cloudshare.com/_
_The Easiest Way to Bring Your Business Application to the Cloud_
@CloudShare https://twitter.com/CloudShare | Blog
http://blog.cloudshare.com/ | TechBlog http://techblog.cld.sr/ |
LinkedIn https://www.linkedin.com/company/cloudshare
